// ===============================================================================
// POWER BI DAX VIRTUAL TABLES FOR ANALYTICS DASHBOARD
// CellphoneS Operational Dashboard - DAX Virtual Tables Specs
// ===============================================================================

// 1. DAX Virtual Table: Store Target Achievement Summary & Status Table
vtable_StoreTargetAchievement = 
ADDCOLUMNS(
    SUMMARIZE(
        processed_transactions,
        processed_stores[Store_ID],
        processed_stores[Store_Name],
        processed_stores[Region],
        processed_stores[Store_Type]
    ),
    "Actual_Revenue", CALCULATE(SUM(processed_transactions[Total_Amount])),
    "Achievement_Pct", DIVIDE(CALCULATE(SUM(processed_transactions[Total_Amount])), 3800000000, 0),
    "Performance_Status", 
        SWITCH(
            TRUE(),
            DIVIDE(CALCULATE(SUM(processed_transactions[Total_Amount])), 3800000000, 0) >= 1.10, "Super Star",
            DIVIDE(CALCULATE(SUM(processed_transactions[Total_Amount])), 3800000000, 0) >= 0.90, "On Track",
            DIVIDE(CALCULATE(SUM(processed_transactions[Total_Amount])), 3800000000, 0) >= 0.75, "Underperforming",
            "Critical Warning"
        )
)

// 2. DAX Virtual Table: Store Type Revenue Allocation Percentage Table
vtable_StoreTypeRevenueAllocation = 
VAR GrandTotalSales = CALCULATE(SUM(processed_transactions[Total_Amount]), ALL(processed_transactions))
RETURN
ADDCOLUMNS(
    SUMMARIZE(
        processed_stores,
        processed_stores[Store_Type]
    ),
    "StoreType_Revenue", CALCULATE(SUM(processed_transactions[Total_Amount])),
    "Grand_Total_Revenue", GrandTotalSales,
    "Revenue_Allocation_Pct", DIVIDE(CALCULATE(SUM(processed_transactions[Total_Amount])), GrandTotalSales, 0)
)
