// ===============================================================================
// POWER BI DAX VIRTUAL TABLES FOR ANALYTICS DASHBOARD
// Part 3 Assessment Requirement: DAX Virtual Tables for Achievement & Allocation
// ===============================================================================

// 1. DAX Virtual Table: Store Target Achievement Summary Table
vtable_StoreTargetAchievement = 
ADDCOLUMNS(
    SUMMARIZE(
        fact_sales,
        dim_store[store_id],
        dim_store[store_name],
        dim_store[region],
        dim_store[store_type]
    ),
    "Actual_Revenue", [Total Sales Revenue],
    "Target_Revenue", [Total Target Revenue],
    "Achievement_Pct", [Revenue Achievement %],
    "Performance_Status", 
        SWITCH(
            TRUE(),
            [Revenue Achievement %] >= 1.10, "Super Star",
            [Revenue Achievement %] >= 0.90, "On Track",
            [Revenue Achievement %] >= 0.70, "Underperforming",
            "Critical Warning"
        )
)

// 2. DAX Virtual Table: Regional Revenue Allocation Matrix Table
vtable_RegionalRevenueAllocation = 
VAR GrandTotalSales = CALCULATE(SUM(fact_sales[total_amount]), ALL(dim_store))
RETURN
ADDCOLUMNS(
    SUMMARIZE(
        dim_store,
        dim_store[region],
        dim_store[regional_sales_manager]
    ),
    "Regional_Revenue", [Total Sales Revenue],
    "Grand_Total_Revenue", GrandTotalSales,
    "Revenue_Allocation_Pct", DIVIDE([Total Sales Revenue], GrandTotalSales, 0)
)
